# Generated by Django 3.1.1 on 2020-09-09 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SensorData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sensor_mac_addr", models.CharField(max_length=50)),
                ("datetime", models.DateTimeField()),
                (
                    "numeric_value",
                    models.DecimalField(decimal_places=3, max_digits=30, null=True),
                ),
                ("string_value", models.TextField(null=True)),
                ("sensor_id", models.CharField(max_length=100)),
            ],
        ),
    ]
