# Generated by Django 3.1.1 on 2020-09-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sensordata",
            name="numeric_value",
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
    ]
