# Generated by Django 3.1.1 on 2020-09-23 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0002_auto_20200910_0040"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sensor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("sensor_id", models.CharField(default="", max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="sensordata",
            name="owner",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="data",
                to="sensors.sensor",
            ),
        ),
    ]
