# Generated by Django 3.1.1 on 2020-09-23 21:14

from django.core.exceptions import ObjectDoesNotExist
from django.db import migrations


def create_sensors(apps, schema_editor):
    Sensor = apps.get_model("sensors", "Sensor")
    SensorData = apps.get_model("sensors", "SensorData")

    for d in SensorData.objects.all():
        try:
            owner = Sensor.objects.get(sensor_id=d.sensor_id)
        except ObjectDoesNotExist:
            owner = Sensor.objects.create(name=d.sensor_id, sensor_id=d.sensor_id)
        d.owner = owner
        d.save()


class Migration(migrations.Migration):

    dependencies = [
        ("sensors", "0003_auto_20200923_2105"),
    ]

    operations = [migrations.RunPython(create_sensors)]
