# Generated by Django 3.1.1 on 2021-06-09 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0004_auto_20200923_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='high_critical',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='high_warn',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
    ]
